INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Rempel Inc', '05672 Champlin Crest', false, 10);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Christiansen - Connelly', '1275 Marvin Extensions', false, 2);   
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Green - Dietrich', '284 Thora Points', false, 5);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Borer - Lindgren', '17361 Kilback Mission', false, 10);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Abernathy, Volkman and Bogisich', '14820 Zella Trail', false, 5);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Reichert - Parisian', '7050 Spinka Grove', true, 6);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Kunde Inc', '64026 Cummings Walk', false, 9);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Wyman - Nienow', '198 Janis River', false, 2);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Wiegand Inc', '90486 Carey Stream', false, 8);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Ullrich and Sons', '48966 Delmer Forks', false, 4);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Quitzon - Connelly', '3018 Jerad Stravenue', true, 9);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Dach - Crist', '7647 Mustafa Trace', false, 7);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Buckridge, Simonis and Ryan', '8916 Tommie Springs', true, 1);   
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Zulauf - Metz', '613 Hintz Villages', false, 10);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Boehm LLC', '647 Hilll Court', true, 6);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Goldner - Brekke', '747 Rohan Points', false, 4);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Kohler, Rice and Shanahan', '781 Howe Springs', false, 2);       
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Schulist - Schmidt', '417 Wilderman Springs', true, 2);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Cole, Harris and Bergnaum', '553 Powlowski Villages', true, 1);
INSERT INTO public.hotel (name, address, is_active, id_city) VALUES ('Hermiston, Corwin and Lang', '1397 Lang Prairie', false, 5);