INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Quas qui eaque fugit modi aliquam dolores.', 69, 46);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (2, 'Rerum magni expedita voluptatem vel pariatur earum inventore ut.', 85, 69);    
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Hic excepturi assumenda aut iure.', 63, 88);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Et nemo et expedita quod odit consequatur quasi cum.', 62, 57);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Quidem quia labore saepe commodi fugiat voluptates repellat.', 62, 53);        
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (4, 'In delectus sit illo quibusdam error recusandae dolore.', 86, 30);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (2, 'Perspiciatis est eos voluptatibus enim beatae.', 56, 24);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Labore quo optio sed repudiandae.', 100, 87);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (3, 'Molestiae voluptatem nemo excepturi blanditiis ipsum quibusdam nemo.', 87, 81);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Rerum vel eos.', 72, 65);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Magni consequuntur aut.', 46, 11);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Dolorem consequuntur minus vel iusto.', 49, 93);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Sapiente quisquam et neque soluta omnis dolorum aut quaerat.', 75, 29);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Doloribus qui a.', 97, 62);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'At atque vel temporibus cum rerum nesciunt.', 73, 13);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Facilis a facere quia magni beatae consequatur facilis non autem.', 64, 70);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (4, 'Consequatur dignissimos itaque quia.', 68, 19);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Illo provident quo.', 78, 39);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Velit aut asperiores ab sint repellendus.', 85, 75);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Cumque explicabo et qui qui.', 48, 22);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Ut ut voluptas temporibus nisi aut.', 77, 14);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (2, 'Doloremque reiciendis sit et rerum illo et perspiciatis aut.', 50, 25);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (3, 'Provident suscipit vel.', 100, 87);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (2, 'Minima hic autem quia.', 99, 65);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Qui quos autem sequi non.', 83, 1);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Labore beatae debitis aliquam suscipit.', 99, 69);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (2, 'Provident aut quis ullam itaque est magnam aut.', 59, 95);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (3, 'Delectus ab quasi voluptatem est totam quia laboriosam magni harum.', 86, 79);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Quia tempore fugit at atque error et.', 54, 8);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (3, 'Praesentium atque inventore veniam dolores quidem temporibus consequatur at quo.', 76, 74);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (3, 'Facere officia omnis non vel accusamus quas non omnis.', 47, 66);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Amet aut et incidunt nulla modi incidunt.', 68, 54);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (3, 'Et ut qui est beatae.', 80, 15);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Et natus molestiae.', 54, 27);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Vitae consequuntur magnam sed alias.', 94, 96);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (4, 'Quo corporis dolores.', 75, 7);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Aliquam aut maxime quisquam provident quibusdam quo voluptates et laboriosam.', 69, 39);INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Sit in et.', 82, 73);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Repellat ea omnis aperiam in numquam provident et molestiae.', 54, 36);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (2, 'Architecto ut magnam occaecati minima occaecati facere voluptatem.', 61, 17);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (3, 'Dolorum recusandae ut sit quia rerum eius veritatis.', 66, 33);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (3, 'Aut unde atque.', 70, 62);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Earum ad repellat repudiandae id totam.', 65, 78);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (3, 'Natus vitae dolores sit totam hic minima.', 83, 47);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (2, 'Aut voluptatum officia officia et possimus ut facere earum.', 59, 15);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (2, 'Molestiae eveniet asperiores eligendi quibusdam.', 89, 76);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Magni soluta quia numquam quibusdam aut expedita aliquam at magni.', 89, 50);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (2, 'Ullam officiis cupiditate rerum.', 88, 22);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Aut sapiente quia.', 52, 74);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (4, 'Qui quasi quo.', 94, 92);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Molestiae natus esse voluptas esse est quia vel aperiam in.', 54, 53);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (4, 'Aut aut aut vitae natus nihil dolorem repudiandae iste.', 69, 2);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (4, 'Non quibusdam adipisci sunt iure adipisci voluptas omnis.', 94, 67);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (4, 'Ullam harum sapiente reiciendis.', 52, 94);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (5, 'Laboriosam velit ut pariatur quos magni ipsa.', 79, 95);
INSERT INTO rating (rate, comment, user_id, room_type_id) VALUES (1, 'Aut labore aut illo non reiciendis delectus velit aut.', 54, 66);