INSERT INTO room_option (name, description, price) VALUES ('disintermediate', 'Doloremque et beatae.', 14);
INSERT INTO room_option (name, description, price) VALUES ('Legacy', 'Est blanditiis animi porro deleniti autem possimus sit rerum.', 90);
INSERT INTO room_option (name, description, price) VALUES ('state', 'Molestiae veniam delectus id molestiae quidem voluptatem ut laborum.', 63);
INSERT INTO room_option (name, description, price) VALUES ('Wooden', 'Quod eum quam.', 74);
INSERT INTO room_option (name, description, price) VALUES ('generate', 'Consectetur harum dolor veniam eaque qui nihil dolorem.', 28);
INSERT INTO room_option (name, description, price) VALUES ('generate', 'Deleniti temporibus quisquam placeat maiores voluptas esse.', 59);
INSERT INTO room_option (name, description, price) VALUES ('navigate', 'Perspiciatis dignissimos quidem cumque dolores rerum omnis odit dignissimos.', 76);
INSERT INTO room_option (name, description, price) VALUES ('SAS', 'Aut eligendi omnis delectus voluptas qui officiis ducimus sit quo.', 78);
INSERT INTO room_option (name, description, price) VALUES ('Crescent', 'Quam quisquam dolorem ut nemo voluptates et.', 16);
INSERT INTO room_option (name, description, price) VALUES ('Unbranded', 'Fuga nihil velit.', 62);
INSERT INTO room_option (name, description, price) VALUES ('open-source', 'Maiores incidunt aut itaque iure impedit.', 25);
INSERT INTO room_option (name, description, price) VALUES ('hack', 'Quasi mollitia eius et harum.', 66);
INSERT INTO room_option (name, description, price) VALUES ('navigating', 'In ut quia saepe quod culpa sunt neque.', 94);
INSERT INTO room_option (name, description, price) VALUES ('connecting', 'Facilis provident debitis et qui cum vel.', 25);
INSERT INTO room_option (name, description, price) VALUES ('navigating', 'Id incidunt blanditiis molestias nemo sed dolorum.', 83);
INSERT INTO room_option (name, description, price) VALUES ('circuit', 'Eum labore laudantium.', 74);
INSERT INTO room_option (name, description, price) VALUES ('product', 'Aut ut iure impedit cumque id impedit ad corporis est.', 78);
INSERT INTO room_option (name, description, price) VALUES ('XML', 'Eum voluptatem laborum enim dolorum voluptatibus unde mollitia.', 46);
INSERT INTO room_option (name, description, price) VALUES ('COM', 'Facere tenetur quo totam accusamus omnis debitis architecto.', 86);
INSERT INTO room_option (name, description, price) VALUES ('Generic', 'Enim iste inventore sunt ad et.', 57);
INSERT INTO room_option (name, description, price) VALUES ('Facilitator', 'Est ab earum voluptatem et officiis qui.', 72);
INSERT INTO room_option (name, description, price) VALUES ('Ergonomic', 'Et nihil eum dolores doloremque omnis.', 29);
INSERT INTO room_option (name, description, price) VALUES ('override', 'Rerum quasi laborum nisi corrupti quo est.', 21);
INSERT INTO room_option (name, description, price) VALUES ('haptic', 'Deleniti consequatur molestias et tenetur nihil et ut.', 19);
INSERT INTO room_option (name, description, price) VALUES ('Tennessee', 'Minus in numquam praesentium quia hic id fugiat.', 54);
INSERT INTO room_option (name, description, price) VALUES ('Lead', 'Nisi in ipsam ut quia qui aut distinctio eum.', 74);
INSERT INTO room_option (name, description, price) VALUES ('Infrastructure', 'Eveniet iure iure sit.', 67);
INSERT INTO room_option (name, description, price) VALUES ('Functionality', 'Numquam est dolor ut quo et ipsa cupiditate error dolores.', 55);
INSERT INTO room_option (name, description, price) VALUES ('Streets', 'Non qui velit modi quam sint consequatur esse.', 58);
INSERT INTO room_option (name, description, price) VALUES ('Canada', 'Similique autem ducimus eveniet atque sint quasi.', 74);
INSERT INTO room_option (name, description, price) VALUES ('Small', 'Commodi quia possimus velit modi nihil tempore inventore fuga ut.', 32);
INSERT INTO room_option (name, description, price) VALUES ('RAM', 'Non dolorem magni et aut id delectus.', 98);
INSERT INTO room_option (name, description, price) VALUES ('Knolls', 'Deleniti inventore natus quae deleniti voluptates.', 60);
INSERT INTO room_option (name, description, price) VALUES ('Business-focused', 'A nesciunt nisi quia.', 91);
INSERT INTO room_option (name, description, price) VALUES ('Wooden', 'Sapiente quam id.', 61);
INSERT INTO room_option (name, description, price) VALUES ('distributed', 'Et doloremque reprehenderit debitis in.', 34);
INSERT INTO room_option (name, description, price) VALUES ('overriding', 'Consequatur accusamus quo reiciendis consequatur et.', 63);
INSERT INTO room_option (name, description, price) VALUES ('silver', 'Quas reiciendis quia porro veniam.', 77);
INSERT INTO room_option (name, description, price) VALUES ('database', 'Fugiat molestiae sit ut beatae voluptate.', 75);
INSERT INTO room_option (name, description, price) VALUES ('multi-tasking', 'Fugiat reprehenderit provident asperiores in.', 57);
INSERT INTO room_option (name, description, price) VALUES ('Port', 'Perferendis rem dolor.', 47);
INSERT INTO room_option (name, description, price) VALUES ('indigo', 'Vel modi iste quisquam laborum ut hic quam.', 76);
INSERT INTO room_option (name, description, price) VALUES ('Quality', 'Quia est hic delectus quos reiciendis modi ut laudantium.', 21);
INSERT INTO room_option (name, description, price) VALUES ('Hong', 'Dolorem porro voluptate in autem omnis repudiandae.', 88);
INSERT INTO room_option (name, description, price) VALUES ('online', 'Quis earum voluptas sunt dolorem dolorem fugiat quibusdam commodi.', 74);
INSERT INTO room_option (name, description, price) VALUES ('input', 'Velit porro voluptate voluptatem blanditiis.', 29);
INSERT INTO room_option (name, description, price) VALUES ('mobile', 'Commodi repudiandae cumque quia voluptas beatae.', 72);
INSERT INTO room_option (name, description, price) VALUES ('forecast', 'Eum dolore ut est culpa placeat consequatur commodi.', 29);
INSERT INTO room_option (name, description, price) VALUES ('transmitting', 'Alias qui blanditiis nobis voluptatibus neque corrupti architecto aut.', 86);     
INSERT INTO room_option (name, description, price) VALUES ('Borders', 'Alias totam quia quo eos eos consequatur id.', 25);